#!/usr/bin/env python3

##
## Small python text editor based on the
## Very simple VT100 terminal text editor widget
## Copyright (c) 2015 Paul Sokolovsky (initial code)
## Copyright (c) 2015 Robert Hammelrath (additional code)
## Distributed under MIT License
## Changes:
## - Ported the code to PyBoard and Wipy (still runs on Linux or Darwin)
## It uses VCP_USB on Pyboard and sys.stdin on WiPy, or UART, if selected.
## - changed read keyboard function to comply with char-by-char input
## - added support for TAB, BACKTAB, SAVE, DEL and Backspace joining lines,
## Find, Replace, Goto Line, UNDO, GET file, Auto-Indent, Set Flags,
## Copy/Delete & Paste, Indent, Un-Indent
## - Added mouse support for pointing and scrolling (not WiPy)
## - handling tab (0x09) on reading & writing files,
## - Added a status line and single line prompts for
## Quit, Save, Find, Replace, Flags and Goto
## - moved main into a function with some optional parameters
## - Added multi-file support
##




##define 1 1

import sys, gc

if sys.platform in ("linux", "darwin"):
    import os, signal, tty, termios, select
class Editor:

    KEYMAP = { ## Gets lengthy
    "\x1b[A" : 0x0b,
    "\x1b[B" : 0x0d,
    "\x1b[D" : 0x1f,
    "\x1b[C" : 0x1e,
    "\x1b[H" : 0x10, ## in Linux Terminal
    "\x1bOH" : 0x10, ## Picocom, Minicom
    "\x1b[1~": 0x10, ## Putty
    "\x1b[F" : 0x03, ## Linux Terminal
    "\x1bOF" : 0x03, ## Picocom, Minicom
    "\x1b[4~": 0x03, ## Putty
    "\x1b[5~": 0xfff1,
    "\x1b[6~": 0xfff2,
    "\x03" : 0x04, ## Ctrl-C
    "\r" : 0x0a,
    "\x7f" : 0x08, ## Ctrl-? (127)
    "\x1b[3~": 0x7f,
    "\x1b[Z" : 0x15, ## Shift Tab
    "\x19" : 0x18, ## Ctrl-Y alias to Ctrl-X
    "\x08" : 0x12, ## Ctrl-H

## keys of BASIC functions mapped onto themselves
## may be imitted from KEYMAP
    "\x11" : 0x11, ## Ctrl-Q
    "\n" : 0x0a,
    "\x13" : 0x13, ## Ctrl-S
    "\x06" : 0x06, ## Ctrl-F
    "\x0e" : 0x0e, ## Ctrl-N
    "\x07" : 0x07, ## Ctrl-G
    "\x05" : 0x05, ## Ctrl-E
    "\x1a" : 0x1a, ## Ctrl-Z
    "\x09" : 0x09,
    "\x15" : 0x15, ## Ctrl-U
    "\x18" : 0x18, ## Ctrl-X
    "\x16" : 0x16, ## Ctrl-V
    "\x04" : 0x04, ## Ctrl-D
    "\x0c" : 0x0c, ## Ctrl-L
    "\x14" : 0x14, ## Ctrl-T
    "\x02" : 0x02, ## Ctrl-B
    "\x01" : 0x01, ## Ctrl-A
    "\x17" : 0x17, ## Ctrl-W
    "\x0f" : 0x0f, ## Ctrl-O
## other keys
    "\x1b[1;5H": 0x14, ## Ctrl-Home
    "\x1b[1;5F": 0x02, ## Ctrl-End
    "\x1b[3;5~": 0x18, ## Ctrl-Del


    "\x0b" : 0xfffd,## Ctrl-K


    "\x1b[M" : 0x1b,

    }
## symbols that are shared between instances of Editor
    yank_buffer = []
    find_pattern = ""
    case = "n"

    replc_pattern = ""


    def __init__(self, tab_size, undo_limit):
        self.top_line = self.cur_line = self.row = self.col = self.margin = 0
        self.tab_size = tab_size
        self.changed = ""
        self.message = self.fname = ""
        self.content = [""]
        self.undo = []
        self.undo_limit = max(undo_limit, 0)
        self.undo_zero = 0
        self.autoindent = "y"
        self.mark = None
        self.straight = "y"

        self.write_tabs = "n"


    if sys.platform in ("linux", "darwin"):

        def wr(self,s):
            if isinstance(s, str):
                s = bytes(s, "utf-8")
            os.write(1, s)

        def rd_any(self):
            if sys.implementation.name == "cpython":
                return select.select([self.sdev], [], [], 0)[0] != []
            else:
                return False

        def rd(self):
            while True:
                try: ## WINCH causes interrupt
                    c = os.read(self.sdev,1)
                    flag = c[0]
                    while (flag & 0xc0) == 0xc0: ## utf-8 char collection
                        c += os.read(self.sdev,1)
                        flag <<= 1
                    return c.decode("UTF-8")
                except:
                    if Editor.winch: ## simulate REDRAW key
                        Editor.winch = False
                        return '\x05'

        @staticmethod
        def init_tty(device, baud):
            Editor.org_termios = termios.tcgetattr(device)
            tty.setraw(device)
            Editor.sdev = device
            Editor.winch = False

        @staticmethod
        def deinit_tty():
            termios.tcsetattr(Editor.sdev, termios.TCSANOW, Editor.org_termios)

        @staticmethod
        def signal_handler(sig, frame):
            signal.signal(signal.SIGWINCH, signal.SIG_IGN)
            Editor.winch = True
            return True
    def goto(self, row, col):
        self.wr("\x1b[{};{}H".format(row + 1, col + 1))

    def clear_to_eol(self):
        self.wr("\x1b[0K")

    def cursor(self, onoff):
        self.wr("\x1b[?25h" if onoff else "\x1b[?25l")

    def hilite(self, mode):
        if mode == 1: ## used for the status line
            self.wr("\x1b[1;47m")
        elif mode == 2: ## used for the marked area
            self.wr("\x1b[43m")
        else: ## plain text
            self.wr("\x1b[0m")


    def mouse_reporting(self, onoff):
        self.wr('\x1b[?9h' if onoff else '\x1b[?9l') ## enable/disable mouse reporting


    def scroll_region(self, stop):
        self.wr('\x1b[1;{}r'.format(stop) if stop else '\x1b[r') ## set scrolling range

    def scroll_up(self, scrolling):
        Editor.scrbuf[scrolling:] = Editor.scrbuf[:-scrolling]
        Editor.scrbuf[:scrolling] = [''] * scrolling
        self.goto(0, 0)
        self.wr("\x1bM" * scrolling)

    def scroll_down(self, scrolling):
        Editor.scrbuf[:-scrolling] = Editor.scrbuf[scrolling:]
        Editor.scrbuf[-scrolling:] = [''] * scrolling
        self.goto(Editor.height - 1, 0)
        self.wr("\x1bD" * scrolling)

    def get_screen_size(self):
        self.wr('\x1b[999;999H\x1b[6n')
        pos = ''
        char = self.rd() ## expect ESC[yyy;xxxR
        while char != 'R':
            pos += char
            char = self.rd()
        return [int(i, 10) for i in pos[2:].split(';')]

    def redraw(self, flag):
        self.cursor(False)
        Editor.height, Editor.width = self.get_screen_size()
        Editor.height -= 1
        Editor.scrbuf = [(False,"\x00")] * Editor.height ## force delete
        self.row = min(Editor.height - 1, self.row)

        self.scroll_region(Editor.height)


        self.mouse_reporting(True) ## enable mouse reporting


        if sys.platform in ("linux", "darwin") and sys.implementation.name == "cpython":
            signal.signal(signal.SIGWINCH, Editor.signal_handler)

        if sys.implementation.name == "micropython":
            gc.collect()
            if flag: self.message = "{} Bytes Memory available".format(gc.mem_free())

    def get_input(self): ## read from interface/keyboard one byte each and match against function keys
        while True:
            in_buffer = self.rd()
            if in_buffer == '\x1b': ## starting with ESC, must be fct
                while True:
                    in_buffer += self.rd()
                    c = in_buffer[-1]
                    if c == '~' or (c.isalpha() and c != 'O'):
                        break
            if in_buffer in self.KEYMAP:
                c = self.KEYMAP[in_buffer]
                if c != 0x1b:
                    return c, ""

                else: ## special for mice
                    self.mouse_fct = ord((self.rd())) ## read 3 more chars
                    self.mouse_x = ord(self.rd()) - 33
                    self.mouse_y = ord(self.rd()) - 33
                    if self.mouse_fct == 0x61:
                        return 0x1d, ""
                    elif self.mouse_fct == 0x60:
                        return 0x1c, ""
                    else:
                        return 0x1b, "" ## do nothing but set the cursor

            else:
                return 0, in_buffer

    def display_window(self): ## Update window and status line
## Force cur_line and col to be in the reasonable bounds
        self.cur_line = min(self.total_lines - 1, max(self.cur_line, 0))
## Check if Column is out of view, and align margin if needed
        if self.straight != "y":
            self.col = min(self.col, len(self.content[self.cur_line]))
        if self.col < 0: self.col = 0
        if self.col >= Editor.width + self.margin:
            self.margin = self.col - Editor.width + (Editor.width >> 2)
        elif self.col < self.margin:
            self.margin = max(self.col - (Editor.width >> 2), 0)
## if cur_line is out of view, align top_line to the given row
        if not (self.top_line <= self.cur_line < self.top_line + Editor.height): # Visible?
            self.top_line = max(self.cur_line - self.row, 0)
## in any case, align row to top_line and cur_line
        self.row = self.cur_line - self.top_line
## update_screen
        self.cursor(False)
        i = self.top_line
        for c in range(Editor.height):
            if i == self.total_lines: ## at empty bottom screen part
                if Editor.scrbuf[c] != (False,''):
                    self.goto(c, 0)
                    self.clear_to_eol()
                    Editor.scrbuf[c] = (False,'')
            else:
                l = (self.mark != None and (
                    (self.mark <= i <= self.cur_line) or (self.cur_line <= i <= self.mark)),
                     self.content[i][self.margin:self.margin + Editor.width])
                if l != Editor.scrbuf[c]: ## line changed, print it
                    self.goto(c, 0)
                    if l[0]: self.hilite(2)
                    self.wr(l[1])
                    if len(l[1]) < Editor.width:
                        self.clear_to_eol()
                    if l[0]: self.hilite(0)
                    Editor.scrbuf[c] = l
                i += 1
## display Status-Line
        self.goto(Editor.height, 0)
        self.hilite(1)
        self.wr("{}{} Row: {}/{} Col: {}  {}".format(
            self.changed, self.fname, self.cur_line + 1, self.total_lines,
            self.col + 1, self.message)[:self.width - 1])
        self.clear_to_eol() ## once moved up for mate/xfce4-terminal issue with scroll region
        self.hilite(0)
        self.goto(self.row, self.col - self.margin)
        self.cursor(True)

    def spaces(self, line, pos = None): ## count spaces
        return (len(line) - len(line.lstrip(" ")) if pos == None else ## at line start
                len(line[:pos]) - len(line[:pos].rstrip(" ")))

    def line_range(self):
        return ((self.mark, self.cur_line + 1) if self.mark < self.cur_line else
                (self.cur_line, self.mark + 1))

    def line_edit(self, prompt, default): ## simple one: only 4 fcts
        self.goto(Editor.height, 0)
        self.hilite(1)
        self.wr(prompt)
        self.wr(default)
        self.clear_to_eol()
        res = default
        while True:
            key, char = self.get_input() ## Get Char of Fct.
            if key in (0x0a, 0x09): ## Finis
                self.hilite(0)
                return res
            elif key == 0x11: ## Abort
                self.hilite(0)
                return None
            elif key == 0x08: ## Backspace
                if (len(res) > 0):
                    res = res[:len(res)-1]
                    self.wr('\b \b')
            elif key == 0x7f: ## Delete prev. Entry
                self.wr('\b \b' * len(res))
                res = ''

            elif key == 0x16: ## Get from paste buffer
                if Editor.yank_buffer:
                    self.wr('\b \b' * len(res))
                    res = Editor.yank_buffer[0].strip()[:Editor.width - len(prompt) - 2]
                    self.wr(res)

            elif key == 0: ## character to be added
                if len(prompt) + len(res) < Editor.width - 2:
                    res += char
                    self.wr(char)

    def find_in_file(self, pattern, pos, end):
        Editor.find_pattern = pattern # remember it
        if Editor.case != "y":
            pattern = pattern.lower()
        spos = pos
        for line in range(self.cur_line, end):
            if Editor.case != "y":
                match = self.content[line][spos:].lower().find(pattern)

            else:
                match = self.content[line][spos:].find(pattern)

            if match >= 0: ## Bingo!
                self.col = match + spos
                self.cur_line = line
                return len(pattern)
            spos = 0
        else:
            self.message = "No match: " + pattern
            return -1

    def undo_add(self, lnum, text, key, span = 1):
        self.changed = '*'
        if self.undo_limit > 0 and (
           len(self.undo) == 0 or key == 0 or self.undo[-1][3] != key or self.undo[-1][0] != lnum):
            if len(self.undo) >= self.undo_limit: ## drop oldest undo, if full
                del self.undo[0]
                self.undo_zero -= 1
            self.undo.append([lnum, span, text, key, self.col])

    def delete_lines(self, yank): ## copy marked lines (opt) and delete them
        lrange = self.line_range()
        if yank:
            Editor.yank_buffer = self.content[lrange[0]:lrange[1]]
        self.undo_add(lrange[0], self.content[lrange[0]:lrange[1]], 0, 0) ## undo inserts
        del self.content[lrange[0]:lrange[1]]
        if self.content == []: ## if all was wiped
            self.content = [""] ## add a line
            self.undo[-1][1] = 1 ## tell undo to overwrite this single line
        self.total_lines = len(self.content)
        self.cur_line = lrange[0]
        self.mark = None ## unset line mark

    def handle_edit_keys(self, key, char): ## keys which edit the buffer
        l = self.content[self.cur_line]
        jut = self.col - len(l) ## <0: before text end, = 0 at text end, >0 beyond text end
        if key == 0x0d:

            if self.cur_line < self.total_lines - 1:

                self.cur_line += 1

                if self.cur_line == self.top_line + Editor.height:
                    self.scroll_down(1)

        elif key == 0x0b:

            if self.cur_line > 0:

                self.cur_line -= 1

                if self.cur_line < self.top_line:
                    self.scroll_up(1)

        elif key == 0x1f:

            if self.col == 0 and self.cur_line > 0:
                self.cur_line -= 1
                self.col = len(self.content[self.cur_line])

                if self.cur_line < self.top_line:
                    self.scroll_up(1)

            else:

                self.col -= 1
        elif key == 0x1e:

            if self.straight != "y" and self.col >= len(l) and self.cur_line < self.total_lines - 1:
                self.col = 0
                self.cur_line += 1

                if self.cur_line == self.top_line + Editor.height:
                    self.scroll_down(1)

            else:

                self.col += 1
        elif key == 0x7f:
            if self.mark != None:
                self.delete_lines(False)
            elif self.col < len(l):
                self.undo_add(self.cur_line, [l], 0x7f)
                self.content[self.cur_line] = l[:self.col] + l[self.col + 1:]
            elif (self.cur_line + 1) < self.total_lines: ## test for last line
                self.undo_add(self.cur_line, [l, self.content[self.cur_line + 1]], 0)
                if jut > 0: ## Landfill needed
                    l += ' ' * jut
                self.content[self.cur_line] = l + self.content.pop(self.cur_line + 1)
                self.total_lines -= 1
        elif key == 0x08:
            if self.mark != None:
                self.delete_lines(False)
            elif self.col > 0:
                if jut <= 0: ## if on solid ground
                    self.undo_add(self.cur_line, [l], 0x08)
                    self.content[self.cur_line] = l[:self.col - 1] + l[self.col:]
                self.col -= 1

            elif self.cur_line > 0: # at the start of a line, but not the first
                self.undo_add(self.cur_line - 1, [self.content[self.cur_line - 1], l], 0)
                self.col = len(self.content[self.cur_line - 1])
                self.content[self.cur_line - 1] += self.content.pop(self.cur_line)
                self.cur_line -= 1
                self.total_lines -= 1

        elif key == 0: ## character to be added
            self.mark = None
            self.undo_add(self.cur_line, [l], 0x20 if char == " " else 0x41)
            if jut < 0:
                self.content[self.cur_line] = l[:self.col] + char + l[self.col:]
            else:
                self.content[self.cur_line] = l + ' ' * jut + char
            self.col += len(char)
        elif key == 0x10:
            ni = self.spaces(l)
            self.col = ni if self.col != ni else 0
        elif key == 0x03:
            self.col = len(l)
        elif key == 0xfff1:
            self.cur_line -= Editor.height
        elif key == 0xfff2:
            self.cur_line += Editor.height
        elif key == 0x06:
            pat = self.line_edit("Find: ", Editor.find_pattern)
            if pat:
                self.find_in_file(pat, self.col, self.total_lines)
                self.row = Editor.height >> 1
        elif key == 0x0e:
            if Editor.find_pattern:
                self.find_in_file(Editor.find_pattern, self.col + 1, self.total_lines)
                self.row = Editor.height >> 1
        elif key == 0x07: ## goto line
            line = self.line_edit("Goto Line: ", "")
            if line:
                self.cur_line = int(line) - 1
                self.row = Editor.height >> 1

        elif key == 0x14: ## first line
            self.cur_line = 0
        elif key == 0x02: ## last line
            self.cur_line = self.total_lines - 1
            self.row = Editor.height - 1 ## will be fixed if required

        elif key == 0x01: ## Toggle Autoindent/Statusline/Search case
            pat = self.line_edit("Case Sensitive Search {}, Autoindent {}, Straight Cursor {}"

            ", Tab Size {}, Write Tabs {}"

            ": ".format(Editor.case, self.autoindent, self.straight

            , self.tab_size, self.write_tabs

            ), "")
            try:
                res = [i.strip().lower() for i in pat.split(",")]
                if res[0]: Editor.case = 'y' if res[0][0] == 'y' else 'n'
                if res[1]: self.autoindent = 'y' if res[1][0] == 'y' else 'n'

                if res[2]: self.tab_size = int(res[2])
                if res[3]: self.write_tabs = 'y' if res[3][0] == 'y' else 'n'
                if res[4]: self.straight = 'y' if res[4][0] == 'y' else 'n'

            except:
                pass

        elif key == 0x1b: ## Set Cursor
            if self.mouse_y < Editor.height:
                self.col = self.mouse_x + self.margin
                self.cur_line = self.mouse_y + self.top_line
                if self.mouse_fct in (0x22, 0x30): ## Right/Ctrl button on Mouse
                    self.mark = self.cur_line if self.mark == None else None
        elif key == 0x1c: ##
            if self.top_line > 0:
                self.top_line = max(self.top_line - 3, 0)
                self.cur_line = min(self.cur_line, self.top_line + Editor.height - 1)

                self.scroll_up(3)

        elif key == 0x1d: ##
            if self.top_line + Editor.height < self.total_lines:
                self.top_line = min(self.top_line + 3, self.total_lines - 1)
                self.cur_line = max(self.cur_line, self.top_line)

                self.scroll_down(3)



        elif key == 0xfffd:
            if self.col < len(l): ## ony within text
                opening = "([{<"
                closing = ")]}>"
                level = 0
                pos = self.col
                srch = l[pos]
                i = opening.find(srch)
                if i >= 0: ## at opening bracket, look forward
                    pos += 1
                    match = closing[i]
                    for i in range(self.cur_line, self.total_lines):
                        for c in range(pos, len(self.content[i])):
                            if self.content[i][c] == match:
                                if level == 0: ## match found
                                    self.cur_line, self.col = i, c
                                    return True ## return here instead of ml-breaking
                                else:
                                    level -= 1
                            elif self.content[i][c] == srch:
                                level += 1
                        pos = 0 ## next line starts at 0
                else:
                    i = closing.find(srch)
                    if i >= 0: ## at closing bracket, look back
                        pos -= 1
                        match = opening[i]
                        for i in range(self.cur_line, -1, -1):
                            for c in range(pos, -1, -1):
                                if self.content[i][c] == match:
                                    if level == 0: ## match found
                                        self.cur_line, self.col = i, c
                                        return True ## return here instead of ml-breaking
                                    else:
                                        level -= 1
                                elif self.content[i][c] == srch:
                                    level += 1
                            if i > 0: ## prev line, if any, starts at the end
                                pos = len(self.content[i - 1]) - 1

        elif key == 0x0c:
            self.mark = self.cur_line if self.mark == None else None
        elif key == 0x0a:
            self.mark = None
            self.undo_add(self.cur_line, [l], 0, 2)
            self.content[self.cur_line] = l[:self.col]
            ni = 0
            if self.autoindent == "y": ## Autoindent
                ni = min(self.spaces(l), self.col) ## query indentation
            self.cur_line += 1
            self.content[self.cur_line:self.cur_line] = [' ' * ni + l[self.col:]]
            self.total_lines += 1
            self.col = ni
        elif key == 0x09:

            if self.mark == None:

                ni = self.tab_size - self.col % self.tab_size ## determine spaces to add
                self.undo_add(self.cur_line, [l], 0x09)
                if jut < 0:
                    self.content[self.cur_line] = l[:self.col] + ' ' * ni + l[self.col:]
                else:
                    self.content[self.cur_line] = l + ' ' * (jut + ni)
                self.col += ni

            else:
                lrange = self.line_range()
                self.undo_add(lrange[0], self.content[lrange[0]:lrange[1]], 0xfffe, lrange[1] - lrange[0]) ## undo replaces
                for i in range(lrange[0],lrange[1]):
                    if len(self.content[i]) > 0:
                        self.content[i] = ' ' * (self.tab_size - self.spaces(self.content[i]) % self.tab_size) + self.content[i]

        elif key == 0x15:

            if self.mark == None:

                ni = (self.col - 1) % self.tab_size + 1
                if jut <= 0:
                    ni = min(ni, self.spaces(l, self.col)) ## determine spaces to drop
                    if ni > 0:
                        self.undo_add(self.cur_line, [l], 0x15)
                        self.content[self.cur_line] = l[:self.col - ni] + l[self.col:]
                        self.col -= ni
                else:
                    self.col -= min(ni, jut)

            else:
                lrange = self.line_range()
                self.undo_add(lrange[0], self.content[lrange[0]:lrange[1]], 0xffff, lrange[1] - lrange[0]) ## undo replaces
                for i in range(lrange[0],lrange[1]):
                    ns = self.spaces(self.content[i])
                    if ns > 0:
                        self.content[i] = self.content[i][(ns - 1) % self.tab_size + 1:]


        elif key == 0x12:
            count = 0
            pat = self.line_edit("Replace: ", Editor.find_pattern)
            if pat:
                rpat = self.line_edit("With: ", Editor.replc_pattern)
                if rpat != None: ## start with setting up loop parameters
                    Editor.replc_pattern = rpat
                    q = ''
                    cur_line = self.cur_line ## remember line
                    if self.mark != None: ## Replace in Marked area
                        (self.cur_line, end_line) = self.line_range()
                        self.col = 0
                    else: ## replace from cur_line to end
                        end_line = self.total_lines
                    self.message = "Replace (yes/No/all/quit) ? "
                    while True: ## and go
                        ni = self.find_in_file(pat, self.col, end_line)
                        if ni >= 0: ## Pattern found
                            if q != 'a':
                                self.display_window()
                                key, char = self.get_input() ## Get Char of Fct.
                                q = char.lower()
                            if q == 'q' or key == 0x11:
                                break
                            elif q in ('a','y'):
                                self.undo_add(self.cur_line, [self.content[self.cur_line]], 0)
                                self.content[self.cur_line] = self.content[self.cur_line][:self.col] + rpat + self.content[self.cur_line][self.col + ni:]
                                self.col += len(rpat)
                                count += 1
                            else: ## everything else is no
                                 self.col += 1





                        else: ## not found, quit
                            break
                    self.cur_line = cur_line ## restore cur_line
                    self.message = "'{}' replaced {} times".format(pat, count)

        elif key == 0x18: # delete line or line(s) into buffer
            if self.mark != None: self.delete_lines(True)
        elif key == 0x04: # copy line(s) into buffer
            if self.mark != None:
                lrange = self.line_range()
                Editor.yank_buffer = self.content[lrange[0]:lrange[1]]
                self.mark = None
        elif key == 0x16: ## insert buffer
            if Editor.yank_buffer:
                if self.mark != None: self.delete_lines(False)
                self.undo_add(self.cur_line, None, 0, -len(Editor.yank_buffer))
                self.content[self.cur_line:self.cur_line] = Editor.yank_buffer # insert lines
                self.total_lines += len(Editor.yank_buffer)
        elif key == 0x13:
            fname = self.line_edit("Save File: ", self.fname)
            if fname:
                self.put_file(fname)
                self.changed = '' ## clear change flag
                self.undo_zero = len(self.undo) ## remember state
                if not self.fname: self.fname = fname ## remember (new) name
        elif key == 0x1a:
            if len(self.undo) > 0:
                action = self.undo.pop(-1) ## get action from stack
                if not action[3] in (0xfffe, 0xffff):
                    self.cur_line = action[0] ## wrong for Bkspc of BOL
                self.col = action[4]
                if action[1] >= 0: ## insert or replace line
                    if action[0] < self.total_lines:
                        self.content[action[0]:action[0] + action[1]] = action[2] # insert lines
                    else:
                        self.content += action[2]
                else: ## delete lines
                    del self.content[action[0]:action[0] - action[1]]
                self.total_lines = len(self.content) ## brute force
                if len(self.undo) == self.undo_zero: self.changed = ''
                self.mark = None
        elif key == 0x05:
            self.redraw(True)

    def edit_loop(self): ## main editing loop
        if not self.content: ## ensure content
            self.content = [""]
        self.total_lines = len(self.content)
        self.redraw(self.message == "")

        while True:
            if not self.rd_any(): ## skip update if a char is waiting
                self.display_window() ## Update & display window
            key, char = self.get_input() ## Get Char of Fct-key code
            self.message = '' ## clear message

            if key == 0x11:
                if self.changed:
                    res = self.line_edit("Content changed! Quit without saving (y/N)? ", "N")
                    if not res or res[0].upper() != 'Y':
                        continue

                self.scroll_region(0)


                self.mouse_reporting(False) ## disable mouse reporting

                self.goto(Editor.height, 0)
                self.clear_to_eol()
                self.undo = []
                return key
            elif key in (0x17, 0x0f):
                return key
            else:
                self.handle_edit_keys(key, char)

## packtabs: replace sequence of space by tab

    def packtabs(self, s):

        try: from uio import StringIO
        except: from _io import StringIO

        sb = StringIO()
        for i in range(0, len(s), 8):
            c = s[i:i + 8]
            cr = c.rstrip(" ")
            if (len(c) - len(cr)) > 1:
                sb.write(cr + "\t") ## Spaces at the end of a section
            else: sb.write(c)
        return sb.getvalue()

## Read file into content
    def get_file(self, fname):
        from os import listdir
        try: from uos import stat
        except: from os import stat
        if not fname:
            fname = self.line_edit("Open file: ", "")
        if fname:
            self.fname = fname
            if fname in ('.', '..') or (stat(fname)[0] & 0x4000): ## Dir
                self.content = ["Directory '{}'".format(fname), ""] + sorted(listdir(fname))
            else:
                if True:

                    pass
                if sys.implementation.name == "cpython":
                    with open(fname, errors="ignore") as f:
                        self.content = f.readlines()
                else:

                    with open(fname) as f:
                        self.content = f.readlines()

                Editor.tab_seen = 'n'

                for i in range(len(self.content)): ## strip and convert
                    self.content[i] = expandtabs(self.content[i].rstrip('\r\n\t '))

                self.write_tabs = Editor.tab_seen


## write file
    def put_file(self, fname):
        if True:

            pass
        if sys.platform in ("linux", "darwin"):
            from os import unlink, rename
            remove = unlink
        else:

            from uos import remove, rename
        tmpfile = fname + ".pyetmp"
        with open(tmpfile, "w") as f:
            for l in self.content:

                if self.write_tabs == 'y':
                    f.write(self.packtabs(l) + '\n')
                else:

                    f.write(l + '\n')
        try: remove(fname)
        except: pass
        rename(tmpfile, fname)

## expandtabs: hopefully sometimes replaced by the built-in function
def expandtabs(s):
    try: from uio import StringIO
    except: from _io import StringIO

    if '\t' in s:

        Editor.tab_seen = 'y'

        sb = StringIO()
        pos = 0
        for c in s:
            if c == '\t': ## tab is seen
                sb.write(" " * (8 - pos % 8)) ## replace by space
                pos += 8 - pos % 8
            else:
                sb.write(c)
                pos += 1
        return sb.getvalue()
    else:
        return s

def pye(*content, tab_size = 4, undo = 50, device = 0, baud = 115200):
## prepare content
    gc.collect() ## all (memory) is mine
    slot = [Editor(tab_size, undo)]
    index = 0
    if content:
        for f in content:
            if index: slot.append(Editor(tab_size, undo))
            if type(f) == str and f: ## String = non-empty Filename
                try: slot[index].get_file(f)
                except: slot[index].message = "File not found"
            elif type(f) == list and len(f) > 0 and type(f[0]) == str:
                slot[index].content = f ## non-empty list of strings -> edit
            index += 1
## edit
    Editor.init_tty(device, baud)
    while True:
        try:
            index %= len(slot)
            key = slot[index].edit_loop() ## edit buffer
            if key == 0x11:
                if len(slot) == 1: ## the last man standing is kept
                    break
                del slot[index]
            elif key == 0x0f:
                slot.append(Editor(tab_size, undo))
                index = len(slot) - 1
                slot[index].get_file(None)
            elif key == 0x17:
                index += 1
        except Exception as err:
            slot[index].message = "{!r}".format(err)
## All windows closed, clean up
    Editor.deinit_tty()
    Editor.yank_buffer = []
## close
    return slot[0].content if (slot[0].fname == "") else slot[0].fname


if __name__ == "__main__":
    if sys.platform in ("linux", "darwin"):
        import stat
        fd_tty = 0
        if len(sys.argv) > 1:
            name = sys.argv[1:]
            pye(*name, undo = 500, device=fd_tty)
        else:
            name = ""
            if sys.implementation.name == "cpython":
                mode = os.fstat(0).st_mode
                if stat.S_ISFIFO(mode) or stat.S_ISREG(mode):
                    name = sys.stdin.readlines()
                    os.close(0) ## close and repopen /dev/tty
                    fd_tty = os.open("/dev/tty", os.O_RDONLY) ## memorized, if new fd
                    for i in range(len(name)): ## strip and convert
                        name[i] = expandtabs(name[i].rstrip('\r\n\t '))
            pye(name, undo = 500, device=fd_tty)
    else:
        print ("\nSorry, this OS is not supported (yet)")
